- job:
    name: patrole-base
    parent: devstack-tempest
    description: Patrole base job for admin and Member roles.
    required-projects:
      - name: openstack/tempest
      - name: openstack/patrole
    timeout: 7800
    roles:
      - zuul: openstack-dev/devstack
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*
      - ^patrole/patrole_tempest_plugin/tests/unit/.*$
      - ^releasenotes/.*
      - ^setup.cfg$
    vars:
      devstack_localrc:
        TEMPEST_PLUGINS: "'{{ ansible_user_dir }}/src/git.openstack.org/openstack/patrole'"
      devstack_plugins:
        patrole: git://git.openstack.org/openstack/patrole.git
      devstack_services:
        tempest: true
        neutron: true
      tempest_concurrency: 2
      tempest_test_regex: (?!.*\[.*\bslow\b.*\])(^patrole_tempest_plugin\.tests\.api)
      tox_envlist: all-plugin

- job:
    name: patrole-base-multinode
    parent: legacy-dsvm-base-multinode
    timeout: 7800
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*
      - ^patrole/patrole_tempest_plugin/tests/unit/.*$
      - ^releasenotes/.*
      - ^setup.cfg$
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/patrole
      - openstack/tempest

- job:
    name: patrole-admin
    parent: patrole-base
    description: Patrole job for admin role.
    vars:
      devstack_localrc:
        RBAC_TEST_ROLE: admin

- job:
    name: patrole-member
    parent: patrole-base
    description: Patrole job for Member role.
    # This currently works from stable/pike onward.
    branches:
      - master
      - stable/queens
      - stable/pike
    vars:
      devstack_localrc:
        RBAC_TEST_ROLE: Member

- job:
    name: patrole-member-queens
    parent: patrole-member
    override-checkout: stable/queens

- job:
    name: patrole-member-pike
    parent: patrole-member
    override-checkout: stable/pike

- job:
    name: patrole-multinode-admin
    parent: patrole-base-multinode
    run: playbooks/patrole-multinode-admin/run.yaml
    post-run: playbooks/patrole-multinode-admin/post.yaml
    voting: false
    nodeset: legacy-ubuntu-xenial-2-node

- job:
    name: patrole-multinode-member
    parent: patrole-base-multinode
    run: playbooks/patrole-multinode-member/run.yaml
    post-run: playbooks/patrole-multinode-member/post.yaml
    voting: false
    nodeset: legacy-ubuntu-xenial-2-node

- job:
    name: patrole-py35-member
    parent: patrole-base
    description: Patrole py3 job for Member role.
    vars:
      devstack_localrc:
        # Use Member for py3 because arguably negative testing is more
        # important than admin, which is already covered by patrole-admin job.
        RBAC_TEST_ROLE: Member
        USE_PYTHON3: true
      devstack_services:
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # Without Swift, c-bak cannot run (in the gate at least).
        c-bak: false

- project:
    check:
      jobs:
        - patrole-admin
        - patrole-member
        - patrole-member-queens
        - patrole-member-pike
        - patrole-py35-member
        - patrole-multinode-admin
        - patrole-multinode-member
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - patrole-admin
        - patrole-member
        - patrole-member-queens
        - patrole-member-pike
        - patrole-py35-member
        - openstack-tox-lower-constraints
